import type { Metadata } from "next";
import {
  ClerkProvider,
} from '@clerk/nextjs'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};
import './globals.css'

import Footer from "@/components/Footer";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          
          {children}
          <Footer/> 
        </body>
       
      </html>
    </ClerkProvider>
  )
}

